export const mainTheme = {
	palette: {
		common: {
			black: '#231f20',
			white: '#FFFFFF',
		},
		primary: {
			light: '#FBD346',
			main: '#F5C518',
			dark: '#D6AC15',
		},
	},
	typography: {
		htmlFontSize: 10,
		fontFamily: '"Poppins", sans-serif',
		fontSize: 14,
		fontWeightLight: 300,
		fontWeightRegular: 400,
		fontWeightMedium: 500,
		fontWeightBold: 700,
		h1: {
			fontFamily: '"Poppins", sans-serif',
			fontWeight: 600,
			fontSize: '3rem',
			lineHeight: 1.167,
			letterSpacing: '-0.01562em',
		},
		h2: {
			fontFamily: '"Poppins", sans-serif',
			fontWeight: 500,
			fontSize: '2.4rem',
			lineHeight: 1.2,
			letterSpacing: '-0.00833em',
		},
		h3: {
			fontFamily: '"Poppins", sans-serif',
			fontWeight: 500,
			fontSize: '2rem',
			lineHeight: 1.167,
			letterSpacing: '0em',
		},
		h4: {
			fontFamily: '"Poppins", sans-serif',
			fontWeight: 500,
			fontSize: '1.8rem',
			lineHeight: 1.235,
			letterSpacing: '0.00735em',
		},
		h5: {
			fontFamily: '"Poppins", sans-serif',
			fontWeight: 500,
			fontSize: '1.5rem',
			lineHeight: 2,
			letterSpacing: '-0.03em',
		},
		h6: {
			fontFamily: '"Poppins", sans-serif',
			fontWeight: 500,
			fontSize: '1.25rem',
			lineHeight: 1.6,
			letterSpacing: '0.0075em',
		},
		subtitle1: {
			fontFamily: '"Poppins", sans-serif',
			fontWeight: 500,
			fontSize: '1.6rem',
			lineHeight: 1.75,
			letterSpacing: '0.00938em',
		},
		subtitle2: {
			fontFamily: '"Poppins", sans-serif',
			fontWeight: 600,
			fontSize: '1.4rem',
			lineHeight: 1.3,
			letterSpacing: '0.00714em',
		},
		body1: {
			fontFamily: '"Poppins", sans-serif',
			fontWeight: 400,
			fontSize: '1.6rem',
			lineHeight: 1.5,
			letterSpacing: '0.00938em',
		},
		body2: {
			fontFamily: '"Poppins", sans-serif',
			fontWeight: 500,
			fontSize: '1.4rem',
			lineHeight: 1.43,
			letterSpacing: '0.01071em',
		},
		button: {
			fontFamily: '"Poppins", sans-serif',
			fontWeight: 500,
			fontSize: '1.4rem',
			lineHeight: 1.75,
			letterSpacing: '0.02857em',
			textTransform: 'uppercase',
		},
		caption: {
			fontFamily: '"Poppins", sans-serif',
			fontWeight: 400,
			fontSize: '1.2rem',
			lineHeight: 1.66,
			letterSpacing: '0.03333em',
		},
	},
}
